import React,{useEffect,useState} from'react';import{createRoot}from'react-dom/client';import{Droplets,Sun,Leaf,Hammer,Heart,Clapperboard,Play,RotateCcw,Plus,ChevronRight}from'lucide-react';import'./style.css';

const heroes=[
{name:'Skye',role:'Water Specialist • Visionary',skill:'Water',icon:'💧',images:['/characters/skye/1SKY.jpg','/characters/skye/DNA.jpg','/characters/skye/OUTDOOR.jpg','/characters/skye/PROFILE.jpg','/characters/skye/SKY.jpg']},
{name:'Tsunjè',role:"Water Systems • Pond Architect",skill:'Water Systems',icon:'✨',images:["/characters/tsunje/1TSUNJE.jpg",'/characters/tsunje/POSE.jpg','/characters/tsunje/PROFILE-1.jpg','/characters/tsunje/PROFILE1.jpg','/characters/tsunje/TSUNJE.jpg']},
{name:'JJ',role:'Gardens • Soil • Plant Health',skill:'Earth',icon:'🌱',images:['/characters/jj/FACE.jpg','/characters/jj/FULL.jpg','/characters/jj/OTHER.jpg','/characters/jj/PROFILE-2.jpg','/characters/jj/RJ.jpg']},
{name:'Rhyan',role:'Renewable Energy Specialist',skill:'Renewable Energy',icon:'☀️',images:[]},
{name:'Cyrus',role:'Animal Care Specialist',skill:'Animal Care',icon:'🐐',images:[]},
{name:'Jayce',role:'Treehouse Design & Construction',skill:'Treehouse Systems',icon:'🌳',images:[]},
{name:'Pierre',role:'Elevated Architect',skill:'Treehouse Architecture',icon:'📐',images:['/characters/pierre/ANGLES-1.jpg','/characters/pierre/ANGLES2.jpg','/characters/pierre/FACE-2.jpg','/characters/pierre/FULL-1.jpg','/characters/pierre/PIERRE.jpg']},
{name:'Emmy',role:'The Young Builder',skill:'Building & Construction',icon:'🔨',images:['/characters/emmy/ANGLES-2.jpg','/characters/emmy/EMMY.jpg','/characters/emmy/FACE-3.jpg','/characters/emmy/FULL-ANGLES.jpg','/characters/emmy/FULL-2.jpg']}];
const projects=[
{name:'Rainwater System',cost:15,gain:{water:25},hero:'Skye',icon:'💧'},
{name:'Solar Array',cost:20,gain:{energy:25},hero:'Rhyan',icon:'☀️'},
{name:'Garden Beds',cost:15,gain:{food:25},hero:'JJ',icon:'🌱'},
{name:'Animal Shelter',cost:20,gain:{care:25},hero:'Cyrus',icon:'🐐'},
{name:'Timber Workshop',cost:20,gain:{materials:25},hero:'Emmy',icon:'🔨'}];
const seedScenes=[
{id:1,title:'The Land Before the Build',status:'Idea',duration:'00:45',characters:'Skye, Emmy, JJ',focus:'Vision & planning',notes:'The Heroes arrive at undeveloped land and imagine what it can become.'},
{id:2,title:'Water Finds a Way',status:'Storyboard',duration:'01:10',characters:'Skye, Tsunjè',focus:'Water systems',notes:'Map the slope, stream and rain capture points before building.'},
{id:3,title:'Power From the Sun',status:'Script',duration:'01:00',characters:'Rhyan, Emmy',focus:'Renewable energy',notes:'Rhyan explains the energy plan while Emmy prepares the mounting structure.'}];
function App(){const[tab,setTab]=useState('home');const[state,setState]=useState(()=>JSON.parse(localStorage.getItem('hh-builder')||'{"supplies":100,"water":20,"energy":20,"food":20,"care":20,"materials":20,"built":[]}'));const[scenes,setScenes]=useState(()=>JSON.parse(localStorage.getItem('hh-scenes')||JSON.stringify(seedScenes)));
useEffect(()=>localStorage.setItem('hh-builder',JSON.stringify(state)),[state]);useEffect(()=>localStorage.setItem('hh-scenes',JSON.stringify(scenes)),[scenes]);
const build=p=>{if(state.supplies<p.cost||state.built.includes(p.name))return;setState(s=>{let n={...s,supplies:s.supplies-p.cost,built:[...s.built,p.name]};Object.entries(p.gain).forEach(([k,v])=>n[k]=(n[k]||0)+v);return n})};
const nav=['home','series','makers','builder','episodes','storyboard','bible','about'];
return <><header><button className="brand" onClick={()=>setTab('home')}>🌳 <b>HOMESTEAD</b> <strong>HEROES</strong></button><nav>{nav.map(n=><button className={tab===n?'on':''} onClick={()=>setTab(n)}>{n==='builder'?'Build':n==='makers'?'Meet the Makers':n}</button>)}</nav></header>
{tab==='home'&&<main><section className="hero"><div className="heroShade"><p className="eyebrow">AN ORIGINAL ANIMATED ADVENTURE</p><h1>Build. Grow. Care.<br/><em>Create Together.</em></h1><p>Young builders, engineers and problem-solvers turn open land into a thriving off-grid homestead—one real-world skill at a time.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById('intro-video')?.scrollIntoView({behavior:'smooth'})}><Play/> Watch Intro</button><button onClick={()=>setTab('builder')}><Hammer/> Build the Homestead</button></div></div></section><section className="introSection" id="intro-video"><p className="eyebrow">OFFICIAL SERIES INTRO</p><h2>Welcome to Homestead Heroes</h2><div className="videoFrame"><video controls playsInline preload="metadata" poster=""><source src="/videos/INTRO.mp4" type="video/mp4"/>Your browser does not support HTML5 video.</video></div><p>Build • Grow • Care • Create • Together</p></section><section className="mission"><p>SMALL STEPS • BIG CHANGE</p><h2>Real kids. Real ideas. A brighter tomorrow.</h2><p>Every challenge begins with a question: <b>How can we build it better—together?</b></p></section><Cards/></main>}
{tab==='makers'&&<main className="page"><Title t="Meet the Makers" s="Meet the young minds building the Homestead. Click or tap a character card to flip it and explore their approved visual references."/><div className="makerGrid">{heroes.map(h=><MakerCard key={h.name} hero={h}/>)}</div></main>}
{tab==='builder'&&<main className="page"><Title t="Homestead Builder" s="Start with open land. Combine resources and the Heroes' skills to grow a resilient homestead."/><div className="meters">{['water','energy','food','care','materials'].map(k=><div><span>{k}</span><progress value={state[k]} max="100"/><b>{state[k]}</b></div>)}</div><div className="supplies">🧰 Build Supplies <b>{state.supplies}</b></div><div className="buildGrid">{projects.map(p=><button className={'project '+(state.built.includes(p.name)?'done':'')} onClick={()=>build(p)} disabled={state.built.includes(p.name)}><i>{p.icon}</i><b>{p.name}</b><small>{p.hero} • {p.cost} supplies</small><span>{state.built.includes(p.name)?'BUILT ✓':'BUILD +'}</span></button>)}</div><button className="reset" onClick={()=>setState({supplies:100,water:20,energy:20,food:20,care:20,materials:20,built:[]})}><RotateCcw/> Reset Homestead</button></main>}
{tab==='storyboard'&&<main className="page"><Title t="Production Storyboard Hub" s="From idea → script → storyboard → animation → review → complete."/><div className="toolbar"><button className="primary" onClick={()=>setScenes([...scenes,{id:Date.now(),title:'New Scene',status:'Idea',duration:'00:30',characters:'',focus:'',notes:'Add production notes…'}])}><Plus/> Add Scene</button></div><div className="scenes">{scenes.map((s,i)=><article className="scene"><span className="shot">{String(i+1).padStart(2,'0')}</span><div><input value={s.title} onChange={e=>setScenes(scenes.map(x=>x.id===s.id?{...x,title:e.target.value}:x))}/><p>{s.notes}</p><small>{s.characters||'Assign characters'} • {s.focus||'Add skill focus'}</small></div><select value={s.status} onChange={e=>setScenes(scenes.map(x=>x.id===s.id?{...x,status:e.target.value}:x))}>{['Idea','Script','Storyboard','Animation','Review','Complete'].map(x=><option>{x}</option>)}</select></article>)}</div></main>}
{tab==='bible'&&<main className="page"><Title t="Character Bible & Continuity" s="Canon is the source of truth. Approved character DNA takes priority over visual reference art."/><div className="grid">{heroes.map(h=><article className="card"><h3>{h.icon} {h.name}</h3><p><b>Specialty:</b> {h.role}</p><p><b>Continuity:</b> Preserve established identity and production DNA. Do not redesign unspecified physical traits.</p></article>)}</div></main>}
{tab==='series'&&<main className="page"><Title t="The Series" s="The world begins as undeveloped open land. Ideas become plans; talents become teamwork; teamwork becomes a living homestead."/><div className="arc">{['Open Land','Imagine','Plan','Build','Grow','Thrive'].map((x,i)=><div><b>0{i+1}</b><span>{x}</span><ChevronRight/></div>)}</div><Cards/></main>}
{tab==='episodes'&&<main className="page"><Title t="Episodes" s="Stories where practical skills become adventures."/><div className="grid">{seedScenes.map((s,i)=><article className="card"><small>EPISODE {i+1}</small><h3>{s.title}</h3><p>{s.notes}</p><b>{s.focus}</b></article>)}</div></main>}
{tab==='about'&&<main className="page"><Title t="About Homestead Heroes" s="An animated world built around curiosity, practical knowledge, stewardship and cooperation."/><blockquote>“Working together, we turn ideas into reality.”</blockquote><p className="copy">Homestead Heroes introduces young audiences to water, food systems, construction, renewable energy, animal care and creative problem-solving through character-led adventures.</p></main>}
</>};function MakerCard({hero:h}){const[flipped,setFlipped]=useState(false);const[photo,setPhoto]=useState(0);return <article className={'makerCard '+(flipped?'flipped':'')} onClick={()=>setFlipped(!flipped)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setFlipped(!flipped)}}} tabIndex={0} role="button" aria-label={`Flip ${h.name} character card`}><div className="makerInner"><div className="makerFront"><div className="makerIcon">{h.icon}</div><p className="eyebrow">HOMESTEAD HERO</p><h3>{h.name}</h3><b>{h.skill}</b><p>{h.role}</p><span className="flipHint">CLICK TO VIEW CHARACTER ↻</span></div><div className="makerBack">{h.images.length?<><img src={h.images[photo]} alt={`${h.name} approved character reference ${photo+1}`} onError={e=>{e.currentTarget.style.display='none'}}/><div className="photoDots">{h.images.map((_,i)=><button key={i} className={photo===i?'active':''} aria-label={`Show reference ${i+1}`} onClick={e=>{e.stopPropagation();setPhoto(i)}}>{i+1}</button>)}</div></>:<div className="awaiting"><i>{h.icon}</i><b>{h.name}</b><span>Approved image set awaiting repository asset sync.</span></div>}<span className="flipHint">CLICK TO RETURN ↻</span></div></div></article>}function Title(p){return <div className="title"><p className="eyebrow">HOMESTEAD HEROES</p><h1>{p.t}</h1><p>{p.s}</p></div>}function Cards(){return <section className="features"><article><Droplets/><h3>BUILD & LEARN</h3><p>Water, gardens, clean energy, structures and animal care become hands-on adventures.</p></article><article><Heart/><h3>CARE TOGETHER</h3><p>Every Hero's specialty matters. Collaboration is the superpower.</p></article><article><Clapperboard/><h3>BEHIND THE STORY</h3><p>A production system keeps episodes, scenes and character continuity organized.</p></article></section>}createRoot(document.getElementById('root')!).render(<App/>);